services:
  cloak-browser:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: cloak-browser
    ports:
      - "5900:5900"
      - "9222:9222"
    environment:
      - CLOAK_PROFILE=\
      - CLOAK_PROXY_TYPE=\
      - CLOAK_PROXY_HOST=\
      - CLOAK_PROXY_PORT=\
      - CLOAK_PROXY_USER=\
      - CLOAK_PROXY_PASS=\
      - VNC_PASSWORD=\
      - DISPLAY=:99
      - RESOLUTION=\
    volumes:
      - ./profiles:/app/profiles:ro
      - cloak-data:/app/data
    restart: unless-stopped
    shm_size: 2gb

volumes:
  cloak-data: